POST http://localhost:8080/register/
Content-Type: application/json

{
    "business_name": "Mano a Mano",
    "role": "charity",
    "ein_number": "123456789",
    "image_data": "image_url_here",
    "address": "123 Street",
    "city": "Waukegan",
    "state": "Illinois",
    "zipcode": "60085",
    "phone_number": "1234567890",
    "username": "mano_a_mano",
    "email": "mam@example.com",
    "password": "omgtest123!" 
}

###

POST http://localhost:8080/register/
Content-Type: application/json

{
    "business_name": "Jewel Osco",
    "role": "donor",
    "ein_number": "123456789",
    "image_data": "image_url_here",
    "address": "123 Street",
    "city": "Grayslake",
    "state": "Illinois",
    "zipcode": "60030",
    "phone_number": "1234567890",
    "username": "jewel_osco",
    "email": "jewel@example.com",
    "password": "omgtest123!" 
}

###

POST http://localhost:8080/login/
Content-Type: application/json

{
    "username": "jewel_osco",
    "password": "omgtest123!"
}

###

POST http://localhost:8080/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzExNjg3MTc0LCJpYXQiOjE3MTE2MDA3NzQsImp0aSI6IjQ4NjYzNGNkYjZhNjQxYjRiODNhODRmMjFmNTg1YTczIiwidXNlcl9pZCI6Nn0.Tw4thAmMYiT_VP9OIFRKEWoFiV4y1SA15OTKcyxmFWI