POST http://localhost:8080/register/
Content-Type: application/json

{
    "business_name": "LGBTQ+ Center Lake County",
    "role": "charity",
    "ein_number": "123456789",
    "image_data": "https://lgbtqlc.com/wp-content/uploads/2022/08/vectored.png",
    "address": "123 Lake Street",
    "city": "Grayslake",
    "state": "Illinois",
    "zipcode": "60035",
    "phone_number": "1234567890",
    "username": "lgbtq_center",
    "email": "lgbtq@example.com",
    "password": "omgtest123!" 
}

###

POST http://localhost:8080/register/
Content-Type: application/json

{
    "business_name": "Lewis Market",
    "role": "donor",
    "ein_number": "123456789",
    "image_data": "https://lewisfresh.com/wp-content/uploads/2018/07/lewis-fresh-market-logo-500x219.png",
    "address": "123 Street",
    "city": "Waukegan",
    "state": "Illinois",
    "zipcode": "60030",
    "phone_number": "1234567890",
    "username": "lewis_market",
    "email": "lewis@example.com",
    "password": "omgtest123!" 
}

###

POST http://localhost:8080/login/
Content-Type: application/json

{
    "username": "lgbtq_center",
    "password": "omgtest123!"
}

###

POST http://localhost:8080/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyNDMxMDAxLCJpYXQiOjE3MTIzNDQ2MDEsImp0aSI6IjhjYzE2NGFiNGRjNDRjNjZhNTA2MTUyYTExODMyYzFhIiwidXNlcl9pZCI6MTV9.O-PII8dMedLuzAo7l6W-XaVEpEdo9isAUdf_fkktsv0