POST http://localhost:8080/carts/add_to_cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0OTU2MTA3LCJpYXQiOjE3MTQ4Njk3MDcsImp0aSI6ImNiMTBiYmQ5OTMwNDQzNzY5OWUwNGIyNDcyOWNlODY0IiwidXNlcl9pZCI6N30.bB9UiwRrdapCF7G7C4K2d1IrtQUAU0F42SI8up_UqkM

{
    "donation_id": 6,
    "quantity": 1
}

### 

POST http://localhost:8080/carts/1/update_cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0OTU2MTA3LCJpYXQiOjE3MTQ4Njk3MDcsImp0aSI6ImNiMTBiYmQ5OTMwNDQzNzY5OWUwNGIyNDcyOWNlODY0IiwidXNlcl9pZCI6N30.bB9UiwRrdapCF7G7C4K2d1IrtQUAU0F42SI8up_UqkM

{
  "donation_id": 6,
  "quantity": 0
}

###
POST http://localhost:8080/carts/1/checkout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0Nzc4NjI5LCJpYXQiOjE3MTQ2OTIyMjksImp0aSI6IjQ0MDQyNzFmYTZjOTQ3Yjg5MmVmYzdmMTE0NGY3NDQyIiwidXNlcl9pZCI6MTB9.umjdmyQ7yleBlYyOgRQJtCALicaovNoaaMERbdDyBZI

###
GET http://localhost:8080/carts/cart_for_current_user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0ODM5NTU3LCJpYXQiOjE3MTQ3NTMxNTcsImp0aSI6Ijc4ZWE0NmIyZTI0YjRkYWU5YmU5NWI0ZjFlZWM0NTJmIiwidXNlcl9pZCI6MTB9.dWGNIamKWYQcFVH9OTxeZ9d4dPEfmU29b8SGIgf9F-U

### 

GET http://localhost:8080/orders/18/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NDkyNjU3LCJpYXQiOjE3MTQ0MDYyNTcsImp0aSI6ImQ3NTZmOWNhMWFkYjQ3ZmQ4NGRlYjZmNjc1NTZjOWQxIiwidXNlcl9pZCI6MTd9.QzrPMaoooh5j_0ylzaSotMf3Te0UT421Xu6krpSwoJo