POST http://localhost:8080/donations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3ODc2NTgwLCJpYXQiOjE3MTc3OTAxODAsImp0aSI6IjBiYzM3YjM3ZmIyMjQ5MzI4Mjg0ODA1ZGZjNzQwNjZhIiwidXNlcl9pZCI6OH0.I38dylUDZxR5YwT7MCvhjHLezdyhpCG6g6vr0RMxgCA

{
    "donor_id": 8,
    "title": "Testing 2",
    "image_data": "https://snaped.fns.usda.gov/sites/default/files/seasonal-produce/2018-05/cabbage.jpg",
    "description": "My cabbages!",
    "total_inventory": 10,
    "claimed_inventory": 0,
    "remaining_inventory": 10,
    "pick_up_deadline": "2025-05-04 15:30:00",
    "address": "123 Omg Street",
    "city": "PleaseWrk",
    "state": "Illinois",
    "zipcode": "53729",
    "is_available": true,
    "category": "produce"
}