# Generated by Django 5.0.4 on 2024-04-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_order', '0002_remove_cart_quantity_remove_order_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation_receipt',
            field=models.JSONField(default=dict),
        ),
    ]
