# Generated by Django 5.0.4 on 2024-06-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donationcategory',
            name='donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('produce', 'PRODUCE'), ('canned', 'CANNED'), ('dairy', 'DAIRY'), ('dry', 'DRY'), ('other', 'OTHER')], default='produce', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DonationCategory',
        ),
    ]
