# Generated by Django 5.0.2 on 2024-03-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.CharField(default='test address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='test city', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(default='test state', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(default='donation title', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='zipcode',
            field=models.CharField(default='65434', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='test address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('carted', 'Carted'), ('ordered', 'Ordered')], max_length=20),
        ),
    ]
