# Generated by Django 5.0.2 on 2024-03-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0002_donation_address_donation_city_donation_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='inventory',
            new_name='total_inventory',
        ),
        migrations.CreateModel(
            name='ClaimedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_quantity', models.IntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_connect_app.donation')),
            ],
        ),
    ]
