# Generated by Django 5.0.2 on 2024-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0003_rename_inventory_donation_total_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='claimed_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='remaining_inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClaimedInventory',
        ),
    ]
