# Generated by Django 5.0.3 on 2024-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0004_donation_claimed_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
