# Generated by Django 5.0.3 on 2024-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0004_donation_claimed_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteddonation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
