# Generated by Django 5.0.3 on 2024-03-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0006_remove_cart_quantity_remove_carteddonation_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteddonation',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_connect_app.cart'),
            preserve_default=False,
        ),
    ]
