# Generated by Django 5.0.3 on 2024-03-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0006_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test_username', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
